# Generated by Django 2.2.14 on 2020-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uniq_portal_id', models.CharField(max_length=100)),
                ('hr_uniq_portal_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conversion_box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_uniq_portal_id', models.CharField(max_length=100)),
                ('hr_uniq_portal_id', models.CharField(max_length=100)),
                ('student_msg', models.CharField(max_length=180)),
                ('hr_msg', models.CharField(max_length=180)),
                ('time_frame', models.DateTimeField()),
            ],
        ),
    ]
