# Generated by Django 2.2.14 on 2020-11-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band_status',
            old_name='hr_uniq_portal_id',
            new_name='hr_email',
        ),
        migrations.RenameField(
            model_name='band_status',
            old_name='student_uniq_portal_id',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='conversion_box',
            old_name='hr_uniq_portal_id',
            new_name='hr_email',
        ),
        migrations.RenameField(
            model_name='conversion_box',
            old_name='student_uniq_portal_id',
            new_name='student_email',
        ),
    ]
