# Generated by Django 2.2.14 on 2020-11-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_auto_20201103_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band_status',
            name='hr_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='band_status',
            name='student_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conversion_box',
            name='hr_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conversion_box',
            name='student_email',
            field=models.EmailField(max_length=100),
        ),
    ]
