# Generated by Django 2.2.14 on 2020-11-05 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_auto_20201103_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion_box',
            name='Hrrounwillbe',
            field=models.DateField(default=datetime.datetime(2020, 11, 5, 14, 37, 49, 585738, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversion_box',
            name='hrround',
            field=models.CharField(default='nodata', max_length=180),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversion_box',
            name='hr_msg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='conversion_box',
            name='student_msg',
            field=models.CharField(max_length=500),
        ),
    ]
