# Generated by Django 2.2.14 on 2020-11-06 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_auto_20201106_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion_box',
            name='Hrrounwillbe',
            field=models.DateField(default=datetime.datetime(2020, 11, 6, 6, 38, 26, 209519, tzinfo=utc)),
        ),
    ]
