# Generated by Django 2.2.14 on 2020-11-06 06:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_auto_20201106_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion_box',
            name='Hrrounwillbe',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
