# Generated by Django 2.2.14 on 2020-11-03 05:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hr_managment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='hr_detailes',
            name='hr_dob',
        ),
        migrations.RemoveField(
            model_name='hr_detailes',
            name='hr_joining_date',
        ),
        migrations.AddField(
            model_name='hr_detailes',
            name='hr_company_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hr_detailes',
            name='hr_password',
            field=models.CharField(default=datetime.datetime(2020, 11, 3, 5, 15, 13, 768972, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
