# Generated by Django 2.2.14 on 2020-11-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_managment', '0002_auto_20201103_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr_detailes',
            name='hr_uniq_portal_id',
        ),
    ]
